Update GitHub Actions to build and test to detect crashes

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -13,7 +13,29 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-#    - name: make clean
+    - name: Clean build
+      run: make clean || true
+    
+#    - name: Build (Debug)
+#      run: make BUILD_TYPE=debug
+    
+#    - name: Run watchdog (Debug test)
+#      run: |
+#        timeout --preserve-status 600s ./processWatchdog > debug_watchdog_stdout.log 2> debug_watchdog_stderr.log
+#        cat debug_watchdog_stdout.log
+#        cat debug_watchdog_stderr.log
+    
+#    - name: Clean
 #      run: make clean
-    - name: make
-      run: make
+    
+    - name: Build (Release)
+      run: make BUILD_TYPE=release
+    
+    - name: Run watchdog (Release test)
+      run: |
+        echo "Running processWatchdog..."
+        timeout --signal=SIGUSR1 --preserve-status 600s ./processWatchdog > release_watchdog_stdout.log 2> release_watchdog_stderr.log
+        echo "Standard Output:"
+        cat watchdog_stdout.log
+        echo "Standard Error:"
+        cat watchdog_stderr.log
